version: '3'
services:
  bot:
    image: kingsdev/pokecord.io
    command: start
    volumes:
      - "$CONFIG_LOCATION:/opt/app/config.json"
      - "$POKEMONS_LOCATION:/opt/app/pokemons.json"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "$MONGODB_PORT:27017"